In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn.naive_bayes import BernoulliNB
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
df=pd.read_csv("C:/Users/prith/OneDrive/Documents/1/spam.csv",encoding="latin-1")

In [3]:
df


class                                            message Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [4]:
df.shape

(5572, 5)

In [5]:
np.unique(df["class"])

array(['ham', 'spam'], dtype=object)

In [6]:
np.unique(df["message"])

array([' &lt;#&gt;  in mca. But not conform.',
       ' &lt;#&gt;  mins but i had to stop somewhere first.',
       ' &lt;DECIMAL&gt; m but its not a common car here so its better to buy from china or asia. Or if i find it less expensive. I.ll holla',
       ..., 'ÌÏ thk of wat to eat tonight.', 'ÌÏ v ma fan...',
       'ÌÏ wait 4 me in sch i finish ard 5..'], dtype=object)

In [7]:
x=df["message"].values
y=df["class"].values
cv=CountVectorizer()
x= cv.fit_transform(x)
v=x.toarray()
print(v)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [8]:
fst_col=df.pop("message")
df.insert(0,"message",fst_col)
df

message class Unnamed: 2  \
0     Go until jurong point, crazy.. Available only ...   ham        NaN   
1                         Ok lar... Joking wif u oni...   ham        NaN   
2     Free entry in 2 a wkly comp to win FA Cup fina...  spam        NaN   
3     U dun say so early hor... U c already then say...   ham        NaN   
4     Nah I don't think he goes to usf, he lives aro...   ham        NaN   
...                                                 ...   ...        ...   
5567  This is the 2nd time we have tried 2 contact u...  spam        NaN   
5568              Will Ì_ b going to esplanade fr home?   ham        NaN   
5569  Pity, * was in mood for that. So...any other s...   ham        NaN   
5570  The guy did some bitching but I acted like i'd...   ham        NaN   
5571                         Rofl. Its true to its name   ham        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [9]:
df=df.drop(["Unnamed: 2","Unnamed: 3","Unnamed: 4"],axis=1)
df

message class
0     Go until jurong point, crazy.. Available only ...   ham
1                         Ok lar... Joking wif u oni...   ham
2     Free entry in 2 a wkly comp to win FA Cup fina...  spam
3     U dun say so early hor... U c already then say...   ham
4     Nah I don't think he goes to usf, he lives aro...   ham
...                                                 ...   ...
5567  This is the 2nd time we have tried 2 contact u...  spam
5568              Will Ì_ b going to esplanade fr home?   ham
5569  Pity, * was in mood for that. So...any other s...   ham
5570  The guy did some bitching but I acted like i'd...   ham
5571                         Rofl. Its true to its name   ham

[5572 rows x 2 columns]

In [10]:
train_x = x[:4160]
train_y = y[:4160]
test_x = x[4160:]
test_y = y[4160:]

In [11]:
bnb= BernoulliNB(binarize=0.0)
model=bnb.fit(train_x,train_y)

In [12]:
y_pred_train=bnb.predict(train_x)
y_pred_test=bnb.predict(test_x)

In [13]:
print(bnb.score(train_x, train_y)*100)
print(bnb.score(test_x, test_y)*100)


98.67788461538461
98.22946175637394


In [14]:
from sklearn.metrics import classification_report
print(classification_report(train_y, y_pred_train))


              precision    recall  f1-score   support

         ham       0.99      1.00      0.99      3598
        spam       0.99      0.91      0.95       562

    accuracy                           0.99      4160
   macro avg       0.99      0.95      0.97      4160
weighted avg       0.99      0.99      0.99      4160



In [15]:
from sklearn.metrics import classification_report
print(classification_report(test_y, y_pred_test))


              precision    recall  f1-score   support

         ham       0.98      1.00      0.99      1227
        spam       0.99      0.87      0.93       185

    accuracy                           0.98      1412
   macro avg       0.99      0.93      0.96      1412
weighted avg       0.98      0.98      0.98      1412

